---
# =============================================================================
# VARIABLES GLOBALES ANSIBLE
# =============================================================================

# Swarm Configuration
manager_ip: 192.168.56.10

# MariaDB
mariadb_root_password: rootpass123
mariadb_database: glpi
mariadb_user: glpi
mariadb_password: glpipass123

# GLPI
glpi_version: latest
domain_name: glpi.local
